name: Deploy Telegram Bot

on:
  schedule:
    - cron: '0 */4 * * *' # Каждое начало часа, каждые 4 часа
  push:
    branches:
      - main # Автоматический запуск при изменениях в главной ветке

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        if test -f requirements.txt; then
          pip install -r requirements.txt
        fi

    - name: Run the bot
      env:
        TG_TOKEN: ${{ secrets.TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        python bot.py
